FROM python:3.11-slim as builder

RUN apt-get update && apt-get install -y --no-install-recommends \
      gcc \
      build-essential \
      cmake build-essential libboost-dev libxml2-dev \
      python3.11-dev unzip \
      apt-transport-https ca-certificates git \
      sqlite3 pcscd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /cades

COPY ./reqs.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r reqs.txt

WORKDIR /tmp
COPY arch ./arch
RUN cd /tmp/arch && tar -xf linux-amd64_deb.tgz && \
    linux-amd64_deb/install.sh cprocsp-rdr-pcsc cprocsp-rdr-rutoken \
      cprocsp-rdr-cryptoki lsb-cprocsp-devel cprocsp-pki-cades \
      cprocsp-rdr-pcsc
RUN dpkg -i /tmp/arch/linux-amd64_deb/cprocsp-pki-cades-64*.deb
WORKDIR /tmp/src
RUN git clone https://github.com/CryptoPro/pycades.git pycades
RUN cd pycades && mkdir build && cd build && cmake .. && make -j4

RUN cp /tmp/src/pycades/build/pycades.so /opt/cprocsp/lib/amd64/pycades.so

FROM python:3.11-slim

WORKDIR /cades

COPY --from=builder /usr/local/lib/python3.11/site-packages/ /usr/local/lib/python3.11/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /opt/cprocsp /opt/cprocsp
COPY --from=builder /opt/cprocsp/lib/amd64/pycades.so /cades/pycades.so

RUN apt-get update && apt-get install -y --no-install-recommends \
    sqlite3 ca-certificates pcscd

COPY ./diadoc ./diadoc
COPY ./router ./router
COPY ./apisrv.py .
COPY ./backends.py .
COPY ./config.py .
COPY ./const.py .
COPY ./db.py .
COPY ./logger.py .
COPY ./logic.py .
COPY ./middleware.py .
COPY ./sender.py .
COPY ./singleton.py .
COPY ./tools.py .
COPY ./cades.default.yaml ./cades.yaml


#ENTRYPOINT ["python", "apisrv.py"]
